### ISSUE TITLE
query failed

### ISSUE THREAD

**Issue by yxfff** [caretdev/trino-iris#1]
<img width="988" alt="image" src="https://github.com/user-attachments/assets/8327fdd2-82e9-4384-bced-5603e2e510ec">

hi, I can connect to iris but I get an error when executing the query. The error is as shown in the picture above. Please help me find out where the problem lies.

error message：[%msg: < 需要标识符,找到:^SELECT :%qpar(1) FROM :%qpar>]

**Comment by daimor** [comment]
Could you provide more details?
Version of the IRIS
full error

**Comment by yxfff** [comment]
trino version 433
intersystems iris:IRIS for Windows (x86-64) 2024.1 (Build 267.2U) Tue Apr 30 2024 16:41:33 EDT

**error log：**
2024-08-14T09:53:51.601+0800	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20240814_015351_00038_p7tgj.0 failed
io.trino.spi.TrinoException: [SQLCODE: <-1>:<无效 SQL 语句 >]
[Location: <Prepare>]
[%msg: < 需要标识符,找到:^SELECT :%qpar(1) FROM :%qpar>]
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:312)
	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:124)
	at io.trino.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:63)
	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_433____20240814_013928_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: [SQLCODE: <-1>:<无效 SQL 语句 >]
[Location: <Prepare>]
[%msg: < 需要标识符,找到:^SELECT :%qpar(1) FROM :%qpar>]
	at com.intersystems.jdbc.IRISConnection.getServerError(IRISConnection.java:976)
	at com.intersystems.jdbc.IRISConnection.processError(IRISConnection.java:1121)
	at com.intersystems.jdbc.InStream.readMessageInternal(InStream.java:312)
	at com.intersystems.jdbc.InStream.readMessage(InStream.java:201)
	at com.intersystems.jdbc.InStream.readMessage(InStream.java:183)
	at com.intersystems.jdbc.IRISPreparedStatement.prepareInternal(IRISPreparedStatement.java:598)
	at com.intersystems.jdbc.IRISPreparedStatement.prepare(IRISPreparedStatement.java:559)
	at com.intersystems.jdbc.IRISPreparedStatement.<init>(IRISPreparedStatement.java:24)
	at com.intersystems.jdbc.IRISConnection.getOrCreatePossiblyShardedIRISPreparedStatement(IRISConnection.java:1891)
	at com.intersystems.jdbc.IRISConnection.prepareStatement(IRISConnection.java:1422)
	at com.intersystems.jdbc.IRISConnection.prepareStatement(IRISConnection.java:277)
	at io.opentelemetry.instrumentation.jdbc.internal.OpenTelemetryConnection.prepareStatement(OpenTelemetryConnection.java:84)
	at io.trino.plugin.jdbc.ForwardingConnection.prepareStatement(ForwardingConnection.java:54)
	at io.trino.plugin.jdbc.ForwardingConnection.prepareStatement(ForwardingConnection.java:54)
	at io.trino.plugin.jdbc.BaseJdbcClient.getPreparedStatement(BaseJdbcClient.java:1153)
	at io.trino.plugin.jdbc.DefaultQueryBuilder.prepareStatement(DefaultQueryBuilder.java:242)
	at io.trino.plugin.jdbc.BaseJdbcClient.buildSql(BaseJdbcClient.java:479)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.buildSql(ForwardingJdbcClient.java:199)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$buildSql$18(StatisticsAwareJdbcClient.java:220)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:34)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.buildSql(StatisticsAwareJdbcClient.java:220)
	at io.trino.plugin.jdbc.CachingJdbcClient.buildSql(CachingJdbcClient.java:290)
	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:120)
	... 17 more

**Comment by daimor** [comment]
I see that in the error it has `:%qpar` which is totally unexpected in these places, and this replacement happens in the InterSystems JDBC driver itself, and should be used only for parameters, not in trino-iris

I'll try to reproduce it

**Comment by yxfff** [comment]
> I see that in the error it has `:%qpar` which is totally unexpected in these places, and this replacement happens in the InterSystems JDBC driver itself, and should be used only for parameters, not in trino-iris
> 
> I'll try to reproduce it

thank you very much,Waiting for good news, trino-iris is very helpful to me～
